services:
  app:
    build:
      context: .
      image: ljs
    volumes:
      - ./posts:/app/posts
    networks:
      - services
    restart: unless-stopped

networks:
  services:
    external: true
